### ISSUE TITLE
Shell in Container

### ISSUE THREAD

**Issue by rndmh3ro** [noqcks/xeol#22]
**What would you like to be added**:
I want to use xeol in a gitlab-ci pipeline.
However using an image in gitlab-ci requires it to have a shell (bash or sh). Would you be willing to provide another image that has a shell?

**Additional context**:

See this issue: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26501
And the documentation: https://docs.gitlab.com/runner/executors/docker.html#configure-images-and-services

```
The image where your job runs must have a working shell in its operating system PATH. Supported shells are:

    For Linux:
        sh
        bash
        PowerShell Core (pwsh). [Introduced in 13.9](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4021).
```

**Comment by noqcks** [comment]
Available in https://github.com/noqcks/xeol/releases/tag/v0.2.3
