### ISSUE TITLE
👶 Better output (for noobs & newbies) when no "EOL found" 🙏 

### ISSUE THREAD

**Issue by adriens** [noqcks/xeol#38]
**What would you like to be added**:

A better message in case when no EOL found.

**Why is this needed**:

Hi, it would be useful to setup a nice message when no EOL found as some may intiialy thnk that beacuase ne EOL was found the report coudl not be done... while in fact.. it's a good news. Maybe a 👍  or something more explicit that says to the end user that everything is ok... and optionally (when avilable how may before EOL will occure)

# :ticket: Related issue

Thanks to your README, I made this PR : 

- https://github.com/endoflife-date/endoflife.date/pull/2569
- https://github.com/endoflife-date/endoflife.date/pull/2568

**Comment by noqcks** [comment]
Added a ✅ to the string to make it more clear

**Comment by adriens** [comment]
Hi @noqcks , when will the version be available on `brew` :grey_question:

**Comment by noqcks** [comment]
Available in 0.2.5, sorry!

**Comment by adriens** [comment]
:ok_man:

**Comment by noqcks** [comment]
Very nice @adriens! Nice to see someone use it!

**Comment by adriens** [comment]
Happy to hear you like the blog post. Yes, your tool is really very cool.
We'll add it to our pipeline thanks to your GH Action.
You really had a great idea to develp this integration, its makes maintenance a breeze ! Thanks a lot.

Hopefully my blog post will increase `xeol` popularity :crossed_fingers:
